/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   fabric-algolia.js
 *   fabric-algolia.js
 */

/**
 * `fabric-algolia`
 * Algolia search component
 */
declare class FabricAlgolia extends Polymer.Element {

  /**
   * Algolia Application ID
   */
  applicationId: string|null|undefined;

  /**
   * Algolia Api Key
   */
  apiKey: string|null|undefined;

  /**
   * Index
   */
  index: string|null|undefined;

  /**
   * Settings
   */
  settings: object|null|undefined;

  /**
   * Response
   */
  readonly response: object|null|undefined;

  /**
   * Error
   */
  readonly error: object|null|undefined;

  /**
   * Query
   */
  query: string|null|undefined;
}

interface HTMLElementTagNameMap {
  "fabric-algolia": FabricAlgolia;
  "fabric-algolia": FabricAlgolia;
}

/**
 * `fabric-algolia`
 * Algolia search component
 */
declare class FabricAlgolia extends Polymer.Element {

  /**
   * Algolia Application ID
   */
  applicationId: string|null|undefined;

  /**
   * Algolia Api Key
   */
  apiKey: string|null|undefined;

  /**
   * Index
   */
  index: string|null|undefined;

  /**
   * Settings
   */
  settings: object|null|undefined;

  /**
   * Response
   */
  readonly response: object|null|undefined;

  /**
   * Error
   */
  readonly error: object|null|undefined;

  /**
   * Query
   */
  query: string|null|undefined;
}
